version: '3.7'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - type: bind
        source: ./data/html
        target: /usr/share/nginx/html
        read_only: true
      - type: bind
        source: ./data/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    networks:
      - edss-net

networks:
  edss-net:
    name: edss-net

  # certbot:
  #   image: certbot/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
