# Author: Yu Li (yu.li@ifu.baug.ethz.ch)
version: "3.7"

services:
  sp_app:
    build: ./ShinyProxy_Image
    image: cocomcie/shinyproxy:1.0
    ports:
      # change source port to 80 if one wants to
      # expose shinyapp to public on internet
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./log/server:/log"
      - "./log/container:/container-logs"
      - "./config/shinyproxy/application.yml:/opt/shinyproxy/application.yml"
    networks:
      - edss-net

networks:
  edss-net:
    name: edss-net
