proxy:
  port:                    8080
  container-log-path:      /container-logs
  authentication:          simple
  heartbeat-rate:          10000
  heartbeat-timeout:       60000
  admin-groups:            admins
  users:
  - name:                  admin    # username
    password:              edss123  # user's password for login
    groups:                admins   # the user-group it belongs to; users can only access apps that share the same user-group
  - name:                  jack
    password:              guest123
    groups:                scientists
  - name:                  david
    password:              guest123
    groups:                stakeholder
  docker:
      internal-networking: true
      bind-address:        127.0.0.1
      container-network:   "edss-net"
  specs:
  - id:                    01_testApp
    display-name:          Online Groundwater Model
    description:           Application which demonstrates the Shiny app coupling with Modflow program
    container-cmd:         ["R", "-e", "shiny::runApp('/root/shinyapp', host='0.0.0.0', port=3838)"]
    container-image:       cocomcie/test_2dmodel
    container-network:     "${proxy.docker.container-network}"
    access-groups:         [admins, scientists, stakeholder]
  - id:                    02_testApp
    display-name:          Crop Water Demand Calculator
    description:           Application which demonstrates the crop water model in a dashboard layout
    container-cmd:         ["R", "-e", "shiny::runApp('/root/shinyapp', host='0.0.0.0', port=3838)"]
    container-image:       cocomcie/test_ic
    container-network:     "${proxy.docker.container-network}"
    access-groups:         [admins, scientists, stakeholder]
  - id:                    03_testApp
    display-name:          airGR
    description:           Web-app of GR Hydrological Models for Precipitation-Runoff Modelling
    container-cmd:         ["R", "-e", "shiny::runApp('/root/shinyapp', host='0.0.0.0', port=3838)"]
    container-image:       cocomcie/air_gr
    container-network:     "${proxy.docker.container-network}"
    access-groups:         [admins, scientists]   # only user (except admin) belonging to "scientists" can access this app
  - id:                    04_testApp
    display-name:          ViRTUE
    description:           Vulnerability and Risk Assessment Tool for Water Utilities
    container-cmd:         ["R", "-e", "shiny::runApp('/root/shinyapp', host='0.0.0.0', port=3838)"]
    container-image:       cocomcie/virtue
    container-network:     "${proxy.docker.container-network}"
    access-groups:         [admins, scientists]  # only user (except admin) belonging to "stakeholder" can access this app

logging:
  file:
    /log/shinyproxy.log
