proxy:
  port: 8080
  container-log-path: /container-logs
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
      container-network: "edss-net"
  specs:
  - id: 01_testApp
    display-name: Test Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shiny::runApp('/root/shinyapp', host='0.0.0.0', port=3838)"]
    container-image: test_app
    container-network: "${proxy.docker.container-network}"

logging:
  file:
    /log/shinyproxy.log
